apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: kn16nlw2f-python
  janus-idp.io/tekton: kn16nlw2f-python
  backstage.io/kubernetes-id: kn16nlw2f-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: kn16nlw2f-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
